version: '3.10'
services:

    app:
      build:
        context: ../
        dockerfile: ./docker/server/Dockerfile
      ports:
        - '8000:80'
      working_dir: /app

    postgres:
      image: postgres:13.3
      environment:
        POSTGRES_MULTIPLE_DATABASES: sqlalchemy_fastapi,test_sqlalchemy_fastapi
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "python"
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
        - data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper-server

    redis:
      image: redis
      container_name: redis
      restart: unless-stopped
      volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - 6379:6379
      command: redis-server /usr/local/etc/redis/redis.conf


#    kafka_layer-ui:
#        image: 'provectuslabs/kafka_layer-ui'
#        container_name: kafka_layer-ui
#        ports:
#          - 8090:8080
#        restart: always
#        environment:
#          - KAFKA_CLUSTERS_0_NAME=local
#          - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_layer:9092
#          - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#        links:
#          - kafka_layer
#          - zookeeper-server

volumes:
  data: