"""cascade delete for order_items

Revision ID: 75d332cb5fea
Revises: 929606f4644f
Create Date: 2024-02-20 12:48:34.345628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d332cb5fea'
down_revision: Union[str, None] = '929606f4644f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_items_order_id_fkey', 'orders_items', type_='foreignkey')
    op.drop_constraint('orders_items_item_id_fkey', 'orders_items', type_='foreignkey')
    op.create_foreign_key("orders_items_order_id_fkey", 'orders_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("orders_items_item_id_fkey", 'orders_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_items_order_id_fkey", 'orders_items', type_='foreignkey')
    op.drop_constraint("orders_items_item_id_fkey", 'orders_items', type_='foreignkey')
    op.create_foreign_key('orders_items_item_id_fkey', 'orders_items', 'items', ['item_id'], ['id'])
    op.create_foreign_key('orders_items_order_id_fkey', 'orders_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
