"""init tables

Revision ID: 7691458bd16c
Revises: 
Create Date: 2024-02-15 15:41:17.746214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7691458bd16c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=25), nullable=False),
    sa.Column('father_name', sa.String(length=25), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    orderstatusenum = postgresql.ENUM('created', 'in_process', 'done', 'canceled', name='orderstatusenum')
    orderstatusenum.create(op.get_bind())
    op.add_column('orders',
                  sa.Column('status', sa.Enum('created', 'in_process', 'done', 'canceled', name='orderstatusenum'), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('orders', 'status')
    orderstatusenum = postgresql.ENUM('created', 'in_process', 'done', 'canceled', name='orderstatusenum')
    orderstatusenum.drop(op.get_bind())
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('items')
    # ### end Alembic commands ###
